# Generated by Django 2.2.9 on 2020-09-02 12:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reactapp', '0002_books_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='cover',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='cover'),
            preserve_default=False,
        ),
    ]
