# Generated by Django 2.2.9 on 2020-09-02 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactapp', '0003_books_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='publish',
            field=models.DateField(),
        ),
    ]
